### ISSUE TITLE
Develop builds for windows since 8373fe6 broken/corrupted

### ISSUE THREAD

**Issue by NoudL** [Limetric/OpenRCT2.org#45] opened 2020-03-26 13:54 UTC
See this issue https://github.com/OpenRCT2/OpenRCT2/issues/11054

The devs there told me the github builds work fine but the downloads on OpenRCT2.org are messed up. The .exe will not run and the .zip files are corrupted.

**Comment by JarnoVgr** [comment] 2020-03-26 14:01
I was made aware of this problem earlier this morning. It should be fixed for new builds. Please let me know if it'll still happen.

**Comment by NoudL** [comment] 2020-03-26 14:03
7zip gives the error "An attempt was made to move the file pointer before the beginning of the file." not sure if that's helpful

**Comment by JarnoVgr** [comment] 2020-03-26 14:07
Earlier problems were caused by using a wrong file encoding, however, it looks fine now yet it still doesn't work. Thanks for supplying the error message.

**Comment by NoudL** [comment] 2020-03-26 14:11
WinRAR gives:     F:\RCT\OpenRCT2-0.2.5-develop-da2ba0b-windows-x64.zip: Onverwacht einde van archief

**Comment by JarnoVgr** [comment] 2020-03-26 14:58
Should be fixed with new builds. I'll close this issue once a build has been made available.

**Closed** 2020-03-27 10:30 UTC
